
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeviceService", targetNamespace = "http://Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DeviceService {


    /**
     * 
     * @return
     *     returns java.util.List<service.Device>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDevices", targetNamespace = "http://Service/", className = "service.GetAllDevices")
    @ResponseWrapper(localName = "getAllDevicesResponse", targetNamespace = "http://Service/", className = "service.GetAllDevicesResponse")
    @Action(input = "http://Service/DeviceService/getAllDevicesRequest", output = "http://Service/DeviceService/getAllDevicesResponse")
    public List<Device> getAllDevices();

    /**
     * 
     * @param deviceId
     * @return
     *     returns service.Device
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeviceById", targetNamespace = "http://Service/", className = "service.GetDeviceById")
    @ResponseWrapper(localName = "getDeviceByIdResponse", targetNamespace = "http://Service/", className = "service.GetDeviceByIdResponse")
    @Action(input = "http://Service/DeviceService/getDeviceByIdRequest", output = "http://Service/DeviceService/getDeviceByIdResponse")
    public Device getDeviceById(
        @WebParam(name = "deviceId", targetNamespace = "")
        int deviceId);

    /**
     * 
     * @param watt
     * @param deviceId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateWattTotal", targetNamespace = "http://Service/", className = "service.UpdateWattTotal")
    @ResponseWrapper(localName = "updateWattTotalResponse", targetNamespace = "http://Service/", className = "service.UpdateWattTotalResponse")
    @Action(input = "http://Service/DeviceService/updateWattTotalRequest", output = "http://Service/DeviceService/updateWattTotalResponse")
    public boolean updateWattTotal(
        @WebParam(name = "deviceId", targetNamespace = "")
        int deviceId,
        @WebParam(name = "watt", targetNamespace = "")
        double watt);

    /**
     * 
     * @param device
     */
    @WebMethod
    @RequestWrapper(localName = "addDevice", targetNamespace = "http://Service/", className = "service.AddDevice")
    @ResponseWrapper(localName = "addDeviceResponse", targetNamespace = "http://Service/", className = "service.AddDeviceResponse")
    @Action(input = "http://Service/DeviceService/addDeviceRequest", output = "http://Service/DeviceService/addDeviceResponse")
    public void addDevice(
        @WebParam(name = "device", targetNamespace = "")
        Device device);

    /**
     * 
     * @param device
     */
    @WebMethod
    @RequestWrapper(localName = "removeDevice", targetNamespace = "http://Service/", className = "service.RemoveDevice")
    @ResponseWrapper(localName = "removeDeviceResponse", targetNamespace = "http://Service/", className = "service.RemoveDeviceResponse")
    @Action(input = "http://Service/DeviceService/removeDeviceRequest", output = "http://Service/DeviceService/removeDeviceResponse")
    public void removeDevice(
        @WebParam(name = "device", targetNamespace = "")
        Device device);

    /**
     * 
     * @param deviceId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLiveData", targetNamespace = "http://Service/", className = "service.GetLiveData")
    @ResponseWrapper(localName = "getLiveDataResponse", targetNamespace = "http://Service/", className = "service.GetLiveDataResponse")
    @Action(input = "http://Service/DeviceService/getLiveDataRequest", output = "http://Service/DeviceService/getLiveDataResponse")
    public boolean getLiveData(
        @WebParam(name = "deviceId", targetNamespace = "")
        int deviceId);

    /**
     * 
     * @param device
     */
    @WebMethod
    @RequestWrapper(localName = "updateDevice", targetNamespace = "http://Service/", className = "service.UpdateDevice")
    @ResponseWrapper(localName = "updateDeviceResponse", targetNamespace = "http://Service/", className = "service.UpdateDeviceResponse")
    @Action(input = "http://Service/DeviceService/updateDeviceRequest", output = "http://Service/DeviceService/updateDeviceResponse")
    public void updateDevice(
        @WebParam(name = "device", targetNamespace = "")
        Device device);

}
