
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Highscore", targetNamespace = "http://Service/", wsdlLocation = "http://localhost:8080/server/Highscore?wsdl")
public class Highscore_Service
    extends Service
{

    private final static URL HIGHSCORE_WSDL_LOCATION;
    private final static WebServiceException HIGHSCORE_EXCEPTION;
    private final static QName HIGHSCORE_QNAME = new QName("http://Service/", "Highscore");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/server/Highscore?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HIGHSCORE_WSDL_LOCATION = url;
        HIGHSCORE_EXCEPTION = e;
    }

    public Highscore_Service() {
        super(__getWsdlLocation(), HIGHSCORE_QNAME);
    }

    public Highscore_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), HIGHSCORE_QNAME, features);
    }

    public Highscore_Service(URL wsdlLocation) {
        super(wsdlLocation, HIGHSCORE_QNAME);
    }

    public Highscore_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HIGHSCORE_QNAME, features);
    }

    public Highscore_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Highscore_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HighscoreService
     */
    @WebEndpoint(name = "HighscoreServicePort")
    public HighscoreService getHighscoreServicePort() {
        return super.getPort(new QName("http://Service/", "HighscoreServicePort"), HighscoreService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HighscoreService
     */
    @WebEndpoint(name = "HighscoreServicePort")
    public HighscoreService getHighscoreServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Service/", "HighscoreServicePort"), HighscoreService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HIGHSCORE_EXCEPTION!= null) {
            throw HIGHSCORE_EXCEPTION;
        }
        return HIGHSCORE_WSDL_LOCATION;
    }

}
