
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HighscoreService", targetNamespace = "http://Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HighscoreService {


    /**
     * 
     * @return
     *     returns java.util.List<service.Highscore>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllHighscores", targetNamespace = "http://Service/", className = "service.GetAllHighscores")
    @ResponseWrapper(localName = "getAllHighscoresResponse", targetNamespace = "http://Service/", className = "service.GetAllHighscoresResponse")
    @Action(input = "http://Service/HighscoreService/getAllHighscoresRequest", output = "http://Service/HighscoreService/getAllHighscoresResponse")
    public List<Highscore> getAllHighscores();

    /**
     * 
     * @param end
     * @param begin
     * @return
     *     returns java.util.List<service.Highscore>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLimitedHighscores", targetNamespace = "http://Service/", className = "service.GetLimitedHighscores")
    @ResponseWrapper(localName = "getLimitedHighscoresResponse", targetNamespace = "http://Service/", className = "service.GetLimitedHighscoresResponse")
    @Action(input = "http://Service/HighscoreService/getLimitedHighscoresRequest", output = "http://Service/HighscoreService/getLimitedHighscoresResponse")
    public List<Highscore> getLimitedHighscores(
        @WebParam(name = "begin", targetNamespace = "")
        int begin,
        @WebParam(name = "end", targetNamespace = "")
        int end);

    /**
     * 
     * @param highscore
     * @return
     *     returns int
     */
    @WebMethod(operationName = "AddHighscore")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AddHighscore", targetNamespace = "http://Service/", className = "service.AddHighscore")
    @ResponseWrapper(localName = "AddHighscoreResponse", targetNamespace = "http://Service/", className = "service.AddHighscoreResponse")
    @Action(input = "http://Service/HighscoreService/AddHighscoreRequest", output = "http://Service/HighscoreService/AddHighscoreResponse")
    public int addHighscore(
        @WebParam(name = "highscore", targetNamespace = "")
        Highscore highscore);

    /**
     * 
     * @param highscore
     */
    @WebMethod(operationName = "DeleteHighscore")
    @RequestWrapper(localName = "DeleteHighscore", targetNamespace = "http://Service/", className = "service.DeleteHighscore")
    @ResponseWrapper(localName = "DeleteHighscoreResponse", targetNamespace = "http://Service/", className = "service.DeleteHighscoreResponse")
    @Action(input = "http://Service/HighscoreService/DeleteHighscoreRequest", output = "http://Service/HighscoreService/DeleteHighscoreResponse")
    public void deleteHighscore(
        @WebParam(name = "highscore", targetNamespace = "")
        Highscore highscore);

}
